getwd()
rm(list=ls())

# Load text file into local variable called 'data'
data = read.delim(file = 'purchases.txt', header = FALSE, sep = '\t', dec = '.')

# Add headers and interpret the last column as a date, extract year of purchase
colnames(data) = c('customer_id', 'purchase_amount', 'date_of_purchase')
data$date_of_purchase = as.Date(data$date_of_purchase, "%Y-%m-%d")
data$year_of_purchase = as.numeric(format(data$date_of_purchase, "%Y"))
data$days_since       = as.numeric(difftime(time1 = "2016-01-01",
                                            time2 = data$date_of_purchase,
                                            units = "days"))

# Compute key marketing indicators using SQL language
try(require("sqldf") || install.packages("sqldf"));library("sqldf")

# Compute recency, frequency, and average purchase amount
customers_2015 = sqldf("SELECT customer_id,
                               MIN(days_since) AS 'recency',
                               COUNT(*) AS 'frequency',
                               AVG(purchase_amount) AS 'monetary'
                        FROM data GROUP BY 1")

summary(customers_2015)
plot(customers_2015$recency,customers_2015$frequency)
plot(customers_2015$recency,customers_2015$monetary)
plot(customers_2015$frequency,customers_2015$monetary)
# ------ MANAGERIAL SEGMENTATION ---------------------

# segmentation based on recency alone
customers_2015$segment = "NA"
customers_2015$segment[which(customers_2015$recency > 365*2)] = "inactive"
customers_2015$segment[which(customers_2015$recency <= 365*2 & customers_2015$recency > 365)] = "cold"
customers_2015$segment[which(customers_2015$recency <= 365 & customers_2015$recency > 183)] = "warm"
customers_2015$segment[which(customers_2015$recency <= 183)] = "active"

#table(customers_2015$segment)
#aggregate(x = customers_2015[, 2:5], by = list(customers_2015$segment), mean)

# segmentation based on recency and monetary value
customers_2015$segment[which(customers_2015$segment == "warm" & customers_2015$monetary < 60)] = "warm low value"
customers_2015$segment[which(customers_2015$segment == "warm" & customers_2015$monetary >= 60)] = "warm high value"
customers_2015$segment[which(customers_2015$segment == "active" & customers_2015$monetary < 60)] = "active low value"
customers_2015$segment[which(customers_2015$segment == "active" & customers_2015$monetary >= 60)] = "active high value"

# Re-order
customers_2015$segment = factor(x = customers_2015$segment, levels = c("active high value","active low value","warm high value","warm low value", "cold","inactive"))
# Show segmentation results
#table(customers_2014$segment)
pie(table(customers_2015$segment), col = rainbow(24))
aggregate(x = customers_2015[, 2:4], by = list(customers_2015$segment), mean)


# --- SEGMENTING A DATABASE RETROSPECTIVELY ----------------
# Compute key marketing indicators using SQL language

# Compute recency, frequency, and average purchase amount
customers_2014 = sqldf("SELECT customer_id,
                               MIN(days_since) - 365 AS 'recency',
                               COUNT(*) AS 'frequency',
                               AVG(purchase_amount) AS 'monetary'
                        FROM data
                        WHERE days_since > 365
                        GROUP BY 1")

# Complete segment solution using which, and exploiting previous test as input
customers_2014$segment = "NA"
customers_2014$segment[which(customers_2014$recency > 365*2)] = "inactive"
customers_2014$segment[which(customers_2014$recency <= 365*2 & customers_2014$recency > 365)] = "cold"
customers_2014$segment[which(customers_2014$recency <= 365 & customers_2014$recency > 183)] = "warm"
customers_2014$segment[which(customers_2014$recency <= 183)] = "active"
customers_2014$segment[which(customers_2014$segment == "warm" & customers_2014$monetary < 60)] = "warm low value"
customers_2014$segment[which(customers_2014$segment == "warm" & customers_2014$monetary >= 60)] = "warm high value"
customers_2014$segment[which(customers_2014$segment == "active" & customers_2014$monetary < 60)] = "active low value"
customers_2014$segment[which(customers_2014$segment == "active" & customers_2014$monetary >= 60)] = "active high value"

# Re-order factor in a way that makes sense
customers_2014$segment = factor(x = customers_2014$segment, levels = c("active high value","active low value","warm high value","warm low value", "cold","inactive"))
# Show segmentation results
#table(customers_2014$segment)
pie(table(customers_2014$segment), col = rainbow(24))
aggregate(x = customers_2014[, 2:4], by = list(customers_2014$segment), mean)
# --- COMPUTING REVENUE GENERATION PER SEGMENT -------------

# Compute how much revenue is generated by segments
# Notice that people with no revenue in 2015 do NOT appear
revenue_2015 = sqldf("SELECT customer_id, SUM(purchase_amount) AS 'revenue_2015'
                     FROM data
                     WHERE year_of_purchase = 2015
                     GROUP BY 1")
summary(revenue_2015)
# Merge 2015 customers and 2015 revenue 
actual = merge(customers_2015, revenue_2015, all.x = TRUE)
summary(actual)
actual$revenue_2015[is.na(actual$revenue_2015)] = 0
# Show average revenue per customer and per segment
aggregate(x = actual$revenue_2015, by = list(customers_2015$segment), mean)

# Merge 2014 customers and 2015 revenue 
prediction = merge(customers_2014, revenue_2015, all.x = TRUE)
summary(prediction)
prediction$revenue_2015[is.na(prediction$revenue_2015)] = 0

# Show average revenue per customer and per segment
r = aggregate(x = prediction$revenue_2015, by = list(customers_2014$segment), mean)
# Re-order and display results
r = r[order(r$x, decreasing = TRUE), ]
print(r);barplot(r$x, names.arg = r$Group.1)

